gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TOKEN_TTL)%'
    ttl_update: true
    firewall: api
    user_provider: security.user.provider.concrete.app_user_provider
